export const SKILLS = {
  // Front-end
  ts: 'TypeScript',
  js: 'JavaScript',
  react: 'React',
  astro: 'Astro',
  vue: 'Vue.js',
  vuex: 'Vuex',
  reduxToolkit: 'Redux Toolkit',
  redux: 'Redux',
  recoil: 'Recoil',
  jotai: 'Jotai',
  zustand: 'Zustand',
  next: 'Next.js',
  nuxt: 'Nuxt.js',
  svelte: 'Svelte',
  graphql: 'GraphQL',
  apollo: 'Apollo Client',
  swr: 'SWR',
  tanstack: 'TanStack Query',
  axios: 'Axios',
  reactNative: 'React Native',
  jest: 'Jest',
  vitest: 'Vitest',
  cypress: 'Cypress',
  playwright: 'Playwright',
  puppeteer: 'Puppeteer',
  storybook: 'Storybook',

  // Styles e UI
  scss: 'SCSS',
  sass: 'Sass',
  postcss: 'PostCSS',
  antd: 'Ant Design',
  mui: 'Material UI',
  chakra: 'Chakra UI',
  tailwind: 'Tailwind CSS',
  styled: 'Styled Components',
  emotion: 'Emotion',
  framer: 'Framer Motion',

  // Back-end
  go: 'Golang',
  python: 'Python',
  java: 'Java',
  gin: 'Gin',
  gorm: 'GORM',
  node: 'Node.js',
  express: 'Express',
  nest: 'NestJS',
  fastify: 'Fastify',
  typeorm: 'TypeORM',
  prisma: 'Prisma',
  postgres: 'PostgreSQL',
  mysql: 'MySQL',
  mongo: 'MongoDB',
  redis: 'Redis',
  grpc: 'gRPC',
  kafka: 'Kafka',
  microservices: 'Microservices',

  // DevOps e Ferramentas
  nginx: 'Nginx',
  brotli: 'Brotli',
  docker: 'Docker',
  cicd: 'CI/CD',
  k8s: 'Kubernetes',
  bash: 'Bash',
  git: 'Git',
  github: 'GitHub',
  vite: 'Vite',
  webpack: 'Webpack',
  eslint: 'ESLint',
  prettier: 'Prettier',
  husky: 'Husky',
  lintstaged: 'Lint-Staged',
  vscode: 'VS Code',
  figma: 'Figma',

  // Outros
  npm: 'npm',
  yarn: 'Yarn',
  pnpm: 'pnpm',
  bun: 'Bun',
  rollup: 'Rollup',
  parcel: 'Parcel',
  turbo: 'Turborepo',
  nx: 'Nx',
  markdown: 'Markdown',
  yaml: 'YAML',
  json: 'JSON',
  rest: 'REST APIs',
  graphqlSchema: 'GraphQL Schema Design',
  websockets: 'WebSockets',
  webrtc: 'WebRTC',
  jwt: 'JWT',
  oauth: 'OAuth 2.0',
  regex: 'Regular Expressions',
  curl: 'cURL',
  wget: 'Wget',
  make: 'Make',
  tsc: 'TypeScript Compiler',
  nodemon: 'Nodemon',
} as const

export const SKILLS_FRONT_END = [
  SKILLS.ts,
  SKILLS.js,
  SKILLS.react,
  SKILLS.vue,
  SKILLS.vuex,
  SKILLS.reduxToolkit,
  SKILLS.redux,
  SKILLS.recoil,
  SKILLS.jotai,
  SKILLS.zustand,
  SKILLS.next,
  SKILLS.nuxt,
  SKILLS.svelte,
  SKILLS.graphql,
  SKILLS.apollo,
  SKILLS.swr,
  SKILLS.tanstack,
  SKILLS.axios,
  SKILLS.reactNative,
  SKILLS.jest,
  SKILLS.vitest,
  SKILLS.cypress,
  SKILLS.playwright,
  SKILLS.puppeteer,
  SKILLS.storybook,
] as const

export const SKILLS_STYLES = [
  SKILLS.scss,
  SKILLS.sass,
  SKILLS.postcss,
  SKILLS.antd,
  SKILLS.mui,
  SKILLS.chakra,
  SKILLS.tailwind,
  SKILLS.styled,
  SKILLS.emotion,
  SKILLS.framer,
] as const

export const SKILLS_BACK_END = [
  SKILLS.go,
  SKILLS.python,
  SKILLS.java,
  SKILLS.gin,
  SKILLS.gorm,
  SKILLS.node,
  SKILLS.express,
  SKILLS.nest,
  SKILLS.fastify,
  SKILLS.typeorm,
  SKILLS.prisma,
  SKILLS.postgres,
  SKILLS.mysql,
  SKILLS.mongo,
  SKILLS.redis,
  SKILLS.grpc,
  SKILLS.kafka,
  SKILLS.microservices,
] as const

export const SKILLS_DEVOPS = [
  SKILLS.nginx,
  SKILLS.brotli,
  SKILLS.docker,
  SKILLS.cicd,
  SKILLS.k8s,
  SKILLS.bash,
  SKILLS.git,
  SKILLS.github,
  SKILLS.vite,
  SKILLS.webpack,
  SKILLS.eslint,
  SKILLS.prettier,
  SKILLS.husky,
  SKILLS.lintstaged,
  SKILLS.vscode,
  SKILLS.figma,
] as const

export const SKILLS_OTHER = [
  SKILLS.npm,
  SKILLS.yarn,
  SKILLS.pnpm,
  SKILLS.bun,
  SKILLS.rollup,
  SKILLS.parcel,
  SKILLS.turbo,
  SKILLS.nx,
  SKILLS.markdown,
  SKILLS.yaml,
  SKILLS.json,
  SKILLS.rest,
  SKILLS.graphqlSchema,
  SKILLS.websockets,
  SKILLS.webrtc,
  SKILLS.jwt,
  SKILLS.oauth,
  SKILLS.regex,
  SKILLS.curl,
  SKILLS.wget,
  SKILLS.make,
  SKILLS.tsc,
  SKILLS.nodemon,
] as const
